### PR TITLE
Added health check

### PR DESCRIPTION
**Pull request by cecton**

### CODE REVIEW

**Comment by langens-jonathan** [comment]
At this point it seems that the health checks are in an (too) immature stage. Without a --start-period flag the check is likely to break (see the TF virtuoso docker) as this health check will just forward any ASK query to the DB hence the result is similar. With the --start-period flag the health check is broken on hub.docker.com. This appears to be an impasse at the moment.

As it currently is uncertain whether or not the docker health checks will become stable and offer the needed features it is dangerous to leave the health check as is from an architectural point of view.

Further, although not a critical point at all, the docker toolings (more specifically inspect) seem to support JSON as an output format. As our framework tends to standardize on JSON API and this format is supported by the tooling it seems only natural to embrace this should we be willing to go forward with the health checks.

As you know something similar, but more expressive and with more functionality, is being developed on BDE. I don't know if you contributed to the BDE init-daemon yourself but I suspect you are aware of it. At the moment, since this exists, it appears to be a better idea to develop this idea further as we are doing.

**Comment by cecton** [comment]
Thanks for the explanation. It would have been better earlier and in a revert commit's message, it prevents misunderstanding. https://github.com/tenforce/docker-virtuoso/commit/616e623188d1d5c2f9a47f576beaecb6bd037d59

**Comment by langens-jonathan** [comment]
This is entirely my bad. But the revert makes no sense as the **entire** code and functionality needed to be removed. I should not have merged it in the first place since the commit was breaking and unnecessary. A force push was the only way to rectify my mistake.

**Comment by cecton** [comment]
You won't convince me Vader, I know the truth

git push --force

**Pull request merged**
